# Generated by Django 4.0.4 on 2022-05-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='psw',
            new_name='password',
        ),
    ]
