# Generated by Django 4.0.4 on 2022-05-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_daate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
